//
//  PokemonData.swift
//  Pokedex
//
//  Created by Javan.Chen on 2016/8/17.
//  Copyright © 2016年 Javan. All rights reserved.
//

import Foundation

struct Pokemon {
    let number:String
    let name: [String]
    let baseAtt:Double
    let baseDef:Double
    let baseSta:Double
    let type: [Type]
    let fastAttacks: [String]
    let chargeAttacks: [String]
    
    var indiAtk:Double
    var indiDef:Double
    var indiSta:Double
    
    var CPM:Double
    var stardust:Double
    var candy:Double
    var minCp:Double
    var maxCp:Double
    var cp:Double {
        didSet {
            calculateIndiValue()
        }
    }
    var minHp:Double
    var maxHp:Double
    var hp:Double {
        didSet {
            calculateIndiValue()
        }
    }
    var level:Double {
        didSet {
            CPM = levelData[level]!["CPM"]!
            stardust = levelData[level]!["stardust"]!
            candy = levelData[level]!["Candies"]!
            
            minHp = Double(lround(baseSta * CPM > 10 ? baseSta * CPM : 10))
            maxHp = Double(lround((baseSta + 15) * CPM > 10 ? (baseSta + 15) * CPM : 10))
            hp = min(max(hp, minHp),maxHp)
            
            minCp = Double(lround(baseAtt * pow(baseDef,0.5) * pow(baseSta,0.5) * pow(CPM, 2) / 10))
            minCp = minCp > 10 ? minCp : 10
            maxCp = (baseAtt + 15) * pow((baseDef + 15),0.5) * pow((baseSta + 15),0.5) * pow(CPM, 2) / 10
            maxCp = Double(lround(maxCp))
            maxCp = maxCp > 10 ? maxCp : 10
            cp = min(max(cp, Double(minCp)), Double(maxCp))
        }
    }
    
    init(number:String, baseAtt:Double, baseDef:Double, baseSta:Double, name:[String], type:[Type], fastAttacks:[String], chargeAttacks:[String]){
        self.number = number
        self.name = name
        self.baseAtt = baseAtt
        self.baseDef = baseDef
        self.baseSta = baseSta
        self.type = type
        self.fastAttacks = fastAttacks
        self.chargeAttacks = chargeAttacks
        
        self.indiAtk = 0
        self.indiDef = 0
        self.indiSta = 0
        self.CPM = 0.0
        self.stardust = 0.0
        self.candy = 0.0
        self.minCp = 0.0
        self.maxCp = 0.0
        self.cp = 0.0
        self.minHp = 0.0
        self.maxHp = 0.0
        self.hp = 0.0
        self.level = 20.0
    }
    
    mutating func calculateIndiValue() {
        let CPM = self.CPM
        let baseAtt = self.baseAtt
        let baseDef = self.baseDef
        let baseSta = self.baseSta
        
        // 1. calculate indi sta
        var staRange = [Int]()
        for sta in (0...15) {
            let totalSta = Int((baseSta + Double(sta)) * CPM)
            let hp = Double(totalSta > 10 ? totalSta : 10)
            if hp == self.hp {
                staRange.append(sta)
            }
        }
        self.indiSta = staRange.count == 0 ? 0 : Double(staRange.maxElement()!)
        
        // 2. calculate indi att + def
        let indiSta = self.indiSta
        var adValue = 0
        var closeValue = 10000.0
        for ad in (0...30) {
            let att = Double(ad) / 2
            let def = Double(ad) / 2
            var cp = (baseAtt + att) * pow((baseDef + def),0.5) * pow((baseSta + indiSta),0.5) * pow(CPM, 2) / 10
            cp = Double(Int(cp))
            if abs(cp - self.cp) < closeValue {
                closeValue = abs(cp - self.cp)
                adValue = ad
            }
        }
        self.indiAtk = Double(adValue) / 2
        self.indiDef = Double(adValue) / 2
    }
    
    mutating func possibleIndiValue() -> [[Double]] {
        let CPM = self.CPM
        let baseAtt = self.baseAtt
        let baseDef = self.baseDef
        let baseSta = self.baseSta
        
        // 1. calculate sta range
        var staRange = [Int]()
        for sta in (0...15) {
            let totalSta = Int((baseSta + Double(sta)) * CPM)
            let hp = Double(totalSta > 10 ? totalSta : 10)
            if hp == self.hp {
                staRange.append(sta)
            }
        }
        
        // 2. calculate atk and def range
        var posibleDataArray = [[Double]]()
        for sta in staRange {
            for atk in (0...15) {
                for def in (0...15) {
                    var cp = (baseAtt + Double(atk)) * pow((baseDef + Double(def)),0.5) * pow((baseSta + Double(sta)),0.5) * pow(CPM, 2) / 10
                    cp = Double(Int(cp))
                    if self.cp == cp {
                        posibleDataArray.append([level, Double(atk), Double(def), Double(sta)])
                    }
                }
            }
        }
        return posibleDataArray
    }
}

let pokemonData:[Pokemon] = [
    Pokemon(number: "#001", baseAtt: 126, baseDef: 126, baseSta: 90,
        name: ["Bulbasaur", "妙蛙種子", "奇異種子"],
        type: [Type.Grass, Type.Poison],
        fastAttacks: ["Tackle", "Vine Whip"],
        chargeAttacks: ["Power Whip", "Seed Bomb", "Sludge Bomb"]),
    Pokemon(number: "#002", baseAtt: 156, baseDef: 158, baseSta: 120,
        name: ["Ivysaur", "妙蛙草", "奇異草"],
        type: [Type.Grass, Type.Poison],
        fastAttacks: ["Razor Leaf", "Vine Whip"],
        chargeAttacks: ["Power Whip", "Sludge Bomb", "Solar Beam"]),
    Pokemon(number: "#003", baseAtt: 198, baseDef: 200, baseSta: 160,
        name: ["Venusaur", "妙蛙花", "奇異花"],
        type: [Type.Grass, Type.Poison],
        fastAttacks: ["Razor Leaf", "Vine Whip"],
        chargeAttacks: ["Petal Blizzard", "Sludge Bomb", "Solar Beam"]),
    Pokemon(number: "#004", baseAtt: 128, baseDef: 108, baseSta: 78,
        name: ["Charmander", "小火龍", "小火龍"],
        type: [Type.Fire],
        fastAttacks: ["Ember", "Scratch"],
        chargeAttacks: ["Flame Burst", "Flamethrower", "Flame Charge"]),
    Pokemon(number: "#005", baseAtt: 160, baseDef: 140, baseSta: 116,
        name: ["Charmeleon", "火恐龍", "火恐龍"],
        type: [Type.Fire],
        fastAttacks: ["Ember", "Scratch"],
        chargeAttacks: ["Fire Punch", "Flame Burst", "Flamethrower"]),
    Pokemon(number: "#006", baseAtt: 212, baseDef: 182, baseSta: 156,
        name: ["Charizard", "噴火龍", "噴火龍"],
        type: [Type.Fire, Type.Flying],
        fastAttacks: ["Ember", "Wing Attack"],
        chargeAttacks: ["Dragon Claw", "Fire Blast", "Flamethrower"]),
    Pokemon(number: "#007", baseAtt: 112, baseDef: 142, baseSta: 88,
        name: ["Squirtle", "傑尼龜", "車厘龜"],
        type: [Type.Water],
        fastAttacks: ["Tackle", "Bubble"],
        chargeAttacks: ["Aqua Jet", "Aqua Tail", "Water Pulse"]),
    Pokemon(number: "#008", baseAtt: 144, baseDef: 176, baseSta: 118,
        name: ["Wartortle", "卡咪龜", "卡美龜"],
        type: [Type.Water],
        fastAttacks: ["Bite", "Water Gun"],
        chargeAttacks: ["Aqua Jet", "Hydro Pump", "Ice Beam"]),
    Pokemon(number: "#009", baseAtt: 186, baseDef: 222, baseSta: 158,
        name: ["Blastoise", "水箭龜", "水箭龜"],
        type: [Type.Water],
        fastAttacks: ["Bite", "Water Gun"],
        chargeAttacks: ["Flash Cannon", "Hydro Pump", "Ice Beam"]),
    Pokemon(number: "#010", baseAtt: 62, baseDef: 66, baseSta: 90,
        name: ["Caterpie", "綠毛蟲", "綠毛蟲"],
        type: [Type.Bug],
        fastAttacks: ["Tackle", "Bug Bite"],
        chargeAttacks: ["Struggle"]),
    Pokemon(number: "#011", baseAtt: 56, baseDef: 86, baseSta: 100,
        name: ["Metapod", "鐵甲蛹", "鐵甲蟲"],
        type: [Type.Bug],
        fastAttacks: ["Tackle", "Bug Bite"],
        chargeAttacks: ["Struggle"]),
    Pokemon(number: "#012", baseAtt: 144, baseDef: 144, baseSta: 120,
        name: ["Butterfree", "巴大蝴", "巴他蝶"],
        type: [Type.Bug, Type.Flying],
        fastAttacks: ["Bug Bite", "Confusion"],
        chargeAttacks: ["Bug Buzz", "Psychic", "Signal Beam"]),
    Pokemon(number: "#013", baseAtt: 68, baseDef: 64, baseSta: 80,
        name: ["Weedle", "獨角蟲", "獨角蟲"],
        type: [Type.Bug, Type.Poison],
        fastAttacks: ["Bug Bite", "Poison Sting"],
        chargeAttacks: ["Struggle"]),
    Pokemon(number: "#014", baseAtt: 62, baseDef: 82, baseSta: 90,
        name: ["Kakuna", "鐵殼昆", "鐵殼蛹"],
        type: [Type.Bug, Type.Poison],
        fastAttacks: ["Bug Bite", "Poison Sting"],
        chargeAttacks: ["Struggle"]),
    Pokemon(number: "#015", baseAtt: 144, baseDef: 130, baseSta: 130,
        name: ["Beedrill", "大針蜂", "大針蜂"],
        type: [Type.Bug, Type.Poison],
        fastAttacks: ["Bug Bite", "Poison Jab"],
        chargeAttacks: ["Aerial Ace", "Sludge Bomb", "X-Scissor"]),
    Pokemon(number: "#016", baseAtt: 94, baseDef: 90, baseSta: 80,
        name: ["Pidgey", "波波", "波波"],
        type: [Type.Normal, Type.Flying],
        fastAttacks: ["Tackle", "Quick Attack"],
        chargeAttacks: ["Aerial Ace", "Air Cutter", "Twister"]),
    Pokemon(number: "#017", baseAtt: 126, baseDef: 122, baseSta: 126,
        name: ["Pidgeotto", "比比鳥", "比比鳥"],
        type: [Type.Normal, Type.Flying],
        fastAttacks: ["Steel Wing", "Wing Attack"],
        chargeAttacks: ["Aerial Ace", "Air Cutter", "Twister"]),
    Pokemon(number: "#018", baseAtt: 170, baseDef: 166, baseSta: 166,
        name: ["Pidgeot", "比鵰", "大比鳥"],
        type: [Type.Normal, Type.Flying],
        fastAttacks: ["Steel Wing", "Wing Attack"],
        chargeAttacks: ["Aerial Ace", "Air Cutter", "Hurricane"]),
    Pokemon(number: "#019", baseAtt: 92, baseDef: 86, baseSta: 60,
        name: ["Rattata", "小拉達", "小哥達"],
        type: [Type.Normal],
        fastAttacks: ["Tackle", "Quick Attack"],
        chargeAttacks: ["Body Slam", "Dig", "Hyper Fang"]),
    Pokemon(number: "#020", baseAtt: 146, baseDef: 150, baseSta: 110,
        name: ["Raticate", "拉達", "哥達"],
        type: [Type.Normal],
        fastAttacks: ["Bite", "Quick Attack"],
        chargeAttacks: ["Dig", "Hyper Beam", "Hyper Fang"]),
    Pokemon(number: "#021", baseAtt: 102, baseDef: 78, baseSta: 80,
        name: ["Spearow", "烈雀", "鬼雀"],
        type: [Type.Normal, Type.Flying],
        fastAttacks: ["Peck", "Quick Attack"],
        chargeAttacks: ["Aerial Ace", "Drill Peck", "Twister"]),
    Pokemon(number: "#022", baseAtt: 168, baseDef: 146, baseSta: 130,
        name: ["Fearow", "大嘴雀", "魔雀"],
        type: [Type.Normal, Type.Flying],
        fastAttacks: ["Peck", "Steel Wing"],
        chargeAttacks: ["Aerial Ace", "Twister", "Drill Run"]),
    Pokemon(number: "#023", baseAtt: 112, baseDef: 112, baseSta: 70,
        name: ["Ekans", "阿柏蛇", "阿柏蛇"],
        type: [Type.Poison],
        fastAttacks: ["Acid", "Poison Sting"],
        chargeAttacks: ["Gunk Shot", "Sludge Bomb", "Wrap"]),
    Pokemon(number: "#024", baseAtt: 166, baseDef: 166, baseSta: 120,
        name: ["Arbok", "阿柏怪", "阿柏怪"],
        type: [Type.Poison],
        fastAttacks: ["Acid", "Bite"],
        chargeAttacks: ["Dark Pulse", "Gunk Shot", "Sludge Wave"]),
    Pokemon(number: "#025", baseAtt: 124, baseDef: 108, baseSta: 70,
        name: ["Pikachu", "皮卡丘", "皮卡超"],
        type: [Type.Electric],
        fastAttacks: ["Quick Attack", "Thunder Shock"],
        chargeAttacks: ["Discharge", "Thunder", "Thunderbolt"]),
    Pokemon(number: "#026", baseAtt: 200, baseDef: 154, baseSta: 120,
        name: ["Raichu", "雷丘", "雷超"],
        type: [Type.Electric],
        fastAttacks: ["Spark", "Thunder Shock"],
        chargeAttacks: ["Brick Break", "Thunder", "Thunder Punch"]),
    Pokemon(number: "#027", baseAtt: 90, baseDef: 114, baseSta: 100,
        name: ["Sandshrew", "穿山鼠", "穿山鼠"],
        type: [Type.Ground],
        fastAttacks: ["Mud Shot", "Scratch"],
        chargeAttacks: ["Dig", "Rock Slide", "Rock Tomb"]),
    Pokemon(number: "#028", baseAtt: 150, baseDef: 172, baseSta: 150,
        name: ["Sandslash", "穿山王", "穿山王"],
        type: [Type.Ground],
        fastAttacks: ["Metal Claw", "Mud Shot"],
        chargeAttacks: ["Bulldoze", "Earthquake", "Rock Tomb"]),
    Pokemon(number: "#029", baseAtt: 100, baseDef: 104, baseSta: 110,
        name: ["Nidoran ♀", "尼多蘭", "尼美蘭"],
        type: [Type.Poison],
        fastAttacks: ["Bite", "Poison Sting"],
        chargeAttacks: ["Body Slam", "Poison Fang", "Sludge Bomb"]),
    Pokemon(number: "#030", baseAtt: 132, baseDef: 136, baseSta: 140,
        name: ["Nidorina", "尼多娜", "尼美蘿"],
        type: [Type.Poison],
        fastAttacks: ["Bite", "Poison Sting"],
        chargeAttacks: ["Dig", "Poison Fang", "Sludge Bomb"]),
    Pokemon(number: "#031", baseAtt: 184, baseDef: 190, baseSta: 180,
        name: ["Nidoqueen", "尼多后", "尼美后"],
        type: [Type.Poison, Type.Ground],
        fastAttacks: ["Bite", "Poison Jab"],
        chargeAttacks: ["Earthquake", "Sludge Wave", "Stone Edge"]),
    Pokemon(number: "#032", baseAtt: 110, baseDef: 94, baseSta: 92,
        name: ["Nidoran ♂", "尼多朗", "尼多朗"],
        type: [Type.Poison],
        fastAttacks: ["Peck", "Poison Sting"],
        chargeAttacks: ["Body Slam", "Horn Attack", "Sludge Bomb"]),
    Pokemon(number: "#033", baseAtt: 142, baseDef: 128, baseSta: 122,
        name: ["Nidorino", "尼多力諾", "尼多利"],
        type: [Type.Poison],
        fastAttacks: ["Poison Sting", "Poison Jab"],
        chargeAttacks: ["Dig", "Horn Attack", "Sludge Bomb"]),
    Pokemon(number: "#034", baseAtt: 204, baseDef: 170, baseSta: 162,
        name: ["Nidoking", "尼多王", "尼多王"],
        type: [Type.Poison, Type.Ground],
        fastAttacks: ["Fury Cutter", "Poison Jab"],
        chargeAttacks: ["Earthquake", "Megahorn", "Sludge Wave"]),
    Pokemon(number: "#035", baseAtt: 116, baseDef: 124, baseSta: 140,
        name: ["Clefairy", "皮皮", "皮皮"],
        type: [Type.Fairy],
        fastAttacks: ["Pound", "Zen Headbutt"],
        chargeAttacks: ["Body Slam", "Disarming Voice", "Moonblast"]),
    Pokemon(number: "#036", baseAtt: 178, baseDef: 178, baseSta: 190,
        name: ["Clefable", "皮可西", "皮可斯"],
        type: [Type.Fairy],
        fastAttacks: ["Pound", "Zen Headbutt"],
        chargeAttacks: ["Dazzling Gleam", "Moonblast", "Psychic"]),
    Pokemon(number: "#037", baseAtt: 106, baseDef: 118, baseSta: 76,
        name: ["Vulpix", "六尾", "六尾"],
        type: [Type.Fire],
        fastAttacks: ["Ember", "Quick Attack"],
        chargeAttacks: ["Body Slam", "Flamethrower", "Flame Charge"]),
    Pokemon(number: "#038", baseAtt: 176, baseDef: 194, baseSta: 146,
        name: ["Ninetales", "九尾", "九尾"],
        type: [Type.Fire],
        fastAttacks: ["Ember", "Feint Attack"],
        chargeAttacks: ["Fire Blast", "Flamethrower", "Heat Wave"]),
    Pokemon(number: "#039", baseAtt: 98, baseDef: 54, baseSta: 230,
        name: ["Jigglypuff", "胖丁", "波波球"],
        type: [Type.Normal, Type.Fairy],
        fastAttacks: ["Feint Attack", "Pound"],
        chargeAttacks: ["Body Slam", "Dazzling Gleam", "Disarming Voice"]),
    Pokemon(number: "#040", baseAtt: 168, baseDef: 108, baseSta: 280,
        name: ["Wigglytuff", "胖可丁", "肥波球"],
        type: [Type.Normal, Type.Fairy],
        fastAttacks: ["Feint Attack", "Pound"],
        chargeAttacks: ["Dazzling Gleam", "Hyper Beam", "Play Rough"]),
    Pokemon(number: "#041", baseAtt: 88, baseDef: 90, baseSta: 80,
        name: ["Zubat", "超音蝠", "音波蝠"],
        type: [Type.Poison, Type.Flying],
        fastAttacks: ["Bite", "Quick Attack"],
        chargeAttacks: ["Air Cutter", "Poison Fang", "Sludge Bomb"]),
    Pokemon(number: "#042", baseAtt: 164, baseDef: 164, baseSta: 150,
        name: ["Golbat", "大嘴蝠", "大口蝠"],
        type: [Type.Poison, Type.Flying],
        fastAttacks: ["Bite", "Wing Attack"],
        chargeAttacks: ["Air Cutter", "Poison Fang", "Ominous Wind"]),
    Pokemon(number: "#043", baseAtt: 134, baseDef: 130, baseSta: 90,
        name: ["Oddish", "走路草", "行路草"],
        type: [Type.Grass, Type.Poison],
        fastAttacks: ["Acid", "Razor Leaf"],
        chargeAttacks: ["Moonblast", "Seed Bomb", "Sludge Bomb"]),
    Pokemon(number: "#044", baseAtt: 162, baseDef: 158, baseSta: 120,
        name: ["Gloom", "臭臭花", "怪味花"],
        type: [Type.Grass, Type.Poison],
        fastAttacks: ["Acid", "Razor Leaf"],
        chargeAttacks: ["Moonblast", "Petal Blizzard", "Sludge Bomb"]),
    Pokemon(number: "#045", baseAtt: 202, baseDef: 190, baseSta: 150,
        name: ["Vileplume", "霸王花", "霸王花"],
        type: [Type.Grass, Type.Poison],
        fastAttacks: ["Acid", "Razor Leaf"],
        chargeAttacks: ["Moonblast", "Petal Blizzard", "Solar Beam"]),
    Pokemon(number: "#046", baseAtt: 122, baseDef: 120, baseSta: 70,
        name: ["Paras", "派拉斯", "蘑菇蟲"],
        type: [Type.Bug, Type.Grass],
        fastAttacks: ["Bug Bite", "Scratch"],
        chargeAttacks: ["Cross Poison", "Seed Bomb", "X-Scissor"]),
    Pokemon(number: "#047", baseAtt: 162, baseDef: 170, baseSta: 120,
        name: ["Parasect", "派拉斯特", "巨菇蟲"],
        type: [Type.Bug, Type.Grass],
        fastAttacks: ["Bug Bite", "Fury Cutter"],
        chargeAttacks: ["Cross Poison", "Solar Beam", "X-Scissor"]),
    Pokemon(number: "#048", baseAtt: 108, baseDef: 118, baseSta: 120,
        name: ["Venonat", "毛球", "毛毛蟲"],
        type: [Type.Bug, Type.Poison],
        fastAttacks: ["Bug Bite", "Confusion"],
        chargeAttacks: ["Poison Fang", "Psybeam", "Signal Beam"]),
    Pokemon(number: "#049", baseAtt: 172, baseDef: 154, baseSta: 140,
        name: ["Venomoth", "末入蛾", "魔魯風"],
        type: [Type.Bug, Type.Poison],
        fastAttacks: ["Bug Bite", "Confusion"],
        chargeAttacks: ["Bug Buzz", "Poison Fang", "Psychic"]),
    Pokemon(number: "#050", baseAtt: 108, baseDef: 86, baseSta: 20,
        name: ["Diglett", "地鼠", "地鼠"],
        type: [Type.Ground],
        fastAttacks: ["Mud Slap", "Scratch"],
        chargeAttacks: ["Dig", "Mud Bomb", "Rock Tomb"]),
    Pokemon(number: "#051", baseAtt: 148, baseDef: 140, baseSta: 70,
        name: ["Dugtrio", "三地鼠", "三頭地鼠"],
        type: [Type.Ground],
        fastAttacks: ["Mud Slap", "Sucker Punch"],
        chargeAttacks: ["Earthquake", "Mud Bomb", "Stone Edge"]),
    Pokemon(number: "#052", baseAtt: 104, baseDef: 94, baseSta: 80,
        name: ["Meowth", "喵喵", "喵喵怪"],
        type: [Type.Normal],
        fastAttacks: ["Bite", "Scratch"],
        chargeAttacks: ["Body Slam", "Dark Pulse", "Night Slash"]),
    Pokemon(number: "#053", baseAtt: 156, baseDef: 146, baseSta: 130,
        name: ["Persian", "貓老大", "高寶貓"],
        type: [Type.Normal],
        fastAttacks: ["Feint Attack", "Scratch"],
        chargeAttacks: ["Night Slash", "Play Rough", "Power Gem"]),
    Pokemon(number: "#054", baseAtt: 132, baseDef: 112, baseSta: 100,
        name: ["Psyduck", "可達鴨", "傻鴨"],
        type: [Type.Water],
        fastAttacks: ["Water Gun", "Zen Headbutt"],
        chargeAttacks: ["Aqua Tail", "Cross Chop", "Psybeam"]),
    Pokemon(number: "#055", baseAtt: 194, baseDef: 176, baseSta: 160,
        name: ["Golduck", "哥達鴨", "高超鴨"],
        type: [Type.Water],
        fastAttacks: ["Confusion", "Water Gun"],
        chargeAttacks: ["Hydro Pump", "Ice Beam", "Psychic"]),
    Pokemon(number: "#056", baseAtt: 122, baseDef: 96, baseSta: 80,
        name: ["Mankey", "猴怪", "猴怪"],
        type: [Type.Fighting],
        fastAttacks: ["Karate Chop", "Scratch"],
        chargeAttacks: ["Brick Break", "Cross Chop", "Low Sweep"]),
    Pokemon(number: "#057", baseAtt: 178, baseDef: 150, baseSta: 130,
        name: ["Primeape", "火爆猴", "火爆猴"],
        type: [Type.Fighting],
        fastAttacks: ["Karate Chop", "Low Kick"],
        chargeAttacks: ["Cross Chop", "Low Sweep", "Night Slash"]),
    Pokemon(number: "#058", baseAtt: 156, baseDef: 110, baseSta: 110,
        name: ["Growlithe", "卡蒂狗", "護主犬"],
        type: [Type.Fire],
        fastAttacks: ["Bite", "Ember"],
        chargeAttacks: ["Body Slam", "Flame Wheel", "Flamethrower"]),
    Pokemon(number: "#059", baseAtt: 230, baseDef: 180, baseSta: 180,
        name: ["Arcanine", "風速狗", "奉神犬"],
        type: [Type.Fire],
        fastAttacks: ["Bite", "Fire Fang"],
        chargeAttacks: ["Bulldoze", "Fire Blast", "Flamethrower"]),
    Pokemon(number: "#060", baseAtt: 108, baseDef: 98, baseSta: 80,
        name: ["Poliwag", "蚊香蝌蚪", "蚊香蝌蚪"],
        type: [Type.Water],
        fastAttacks: ["Bubble", "Mud Shot"],
        chargeAttacks: ["Body Slam", "Bubble Beam", "Mud Bomb"]),
    Pokemon(number: "#061", baseAtt: 132, baseDef: 132, baseSta: 130,
        name: ["Poliwhirl", "蚊香蛙", "蚊香蛙"],
        type: [Type.Water],
        fastAttacks: ["Bubble", "Mud Shot"],
        chargeAttacks: ["Bubble Beam", "Mud Bomb", "Scald"]),
    Pokemon(number: "#062", baseAtt: 180, baseDef: 202, baseSta: 180,
        name: ["Poliwrath", "快泳蛙", "大力蛙"],
        type: [Type.Water, Type.Fighting],
        fastAttacks: ["Bubble", "Mud Shot"],
        chargeAttacks: ["Hydro Pump", "Ice Punch", "Submission"]),
    Pokemon(number: "#063", baseAtt: 110, baseDef: 76, baseSta: 50,
        name: ["Abra", "凱西", "卡斯"],
        type: [Type.Psychic],
        fastAttacks: ["Zen Headbutt"],
        chargeAttacks: ["Psyshock", "Shadow Ball", "Signal Beam"]),
    Pokemon(number: "#064", baseAtt: 150, baseDef: 112, baseSta: 80,
        name: ["Kadabra", "勇吉拉", "尤基納"],
        type: [Type.Psychic],
        fastAttacks: ["Confusion", "Psycho Cut"],
        chargeAttacks: ["Dazzling Gleam", "Psybeam", "Shadow Ball"]),
    Pokemon(number: "#065", baseAtt: 186, baseDef: 152, baseSta: 110,
        name: ["Alakazam", "胡地", "富迪"],
        type: [Type.Psychic],
        fastAttacks: ["Confusion", "Psycho Cut"],
        chargeAttacks: ["Dazzling Gleam", "Psychic", "Shadow Ball"]),
    Pokemon(number: "#066", baseAtt: 118, baseDef: 96, baseSta: 140,
        name: ["Machop", "腕力", "鐵腕"],
        type: [Type.Fighting],
        fastAttacks: ["Karate Chop", "Low Kick"],
        chargeAttacks: ["Brick Break", "Cross Chop", "Low Sweep"]),
    Pokemon(number: "#067", baseAtt: 154, baseDef: 144, baseSta: 160,
        name: ["Machoke", "豪力", "大力"],
        type: [Type.Fighting],
        fastAttacks: ["Karate Chop", "Low Kick"],
        chargeAttacks: ["Brick Break", "Cross Chop", "Submission"]),
    Pokemon(number: "#068", baseAtt: 198, baseDef: 180, baseSta: 180,
        name: ["Machamp", "怪力", "怪力"],
        type: [Type.Fighting],
        fastAttacks: ["Bullet Punch", "Karate Chop"],
        chargeAttacks: ["Cross Chop", "Stone Edge", "Submission"]),
    Pokemon(number: "#069", baseAtt: 158, baseDef: 78, baseSta: 100,
        name: ["Bellsprout", "喇叭芽", "喇叭芽"],
        type: [Type.Grass, Type.Poison],
        fastAttacks: ["Acid", "Vine Whip"],
        chargeAttacks: ["Power Whip", "Sludge Bomb", "Wrap"]),
    Pokemon(number: "#070", baseAtt: 190, baseDef: 110, baseSta: 130,
        name: ["Weepinbell", "口呆花", "口呆花"],
        type: [Type.Grass, Type.Poison],
        fastAttacks: ["Acid", "Razor Leaf"],
        chargeAttacks: ["Power Whip", "Seed Bomb", "Sludge Bomb"]),
    Pokemon(number: "#071", baseAtt: 222, baseDef: 152, baseSta: 160,
        name: ["Victreebel", "大食花", "大食花"],
        type: [Type.Grass, Type.Poison],
        fastAttacks: ["Acid", "Razor Leaf"],
        chargeAttacks: ["Sludge Bomb", "Solar Beam", "Leaf Blade"]),
    Pokemon(number: "#072", baseAtt: 106, baseDef: 136, baseSta: 80,
        name: ["Tentacool", "瑪瑙水母", "大眼水母"],
        type: [Type.Water, Type.Poison],
        fastAttacks: ["Bubble", "Poison Sting"],
        chargeAttacks: ["Bubble Beam", "Water Pulse", "Wrap"]),
    Pokemon(number: "#073", baseAtt: 170, baseDef: 196, baseSta: 160,
        name: ["Tentacruel", "毒刺水母", "多腳水母"],
        type: [Type.Water, Type.Poison],
        fastAttacks: ["Acid", "Poison Jab"],
        chargeAttacks: ["Blizzard", "Hydro Pump", "Sludge Wave"]),
    Pokemon(number: "#074", baseAtt: 106, baseDef: 118, baseSta: 80,
        name: ["Geodude", "小拳石", "小拳石"],
        type: [Type.Rock, Type.Ground],
        fastAttacks: ["Tackle", "Rock Throw"],
        chargeAttacks: ["Dig", "Rock Slide", "Rock Tomb"]),
    Pokemon(number: "#075", baseAtt: 142, baseDef: 156, baseSta: 110,
        name: ["Graveler", "隆隆石", "滾動石"],
        type: [Type.Rock, Type.Ground],
        fastAttacks: ["Mud Slap", "Rock Throw"],
        chargeAttacks: ["Dig", "Rock Slide", "Stone Edge"]),
    Pokemon(number: "#076", baseAtt: 176, baseDef: 198, baseSta: 160,
        name: ["Golem", "隆隆岩", "滾動岩"],
        type: [Type.Rock, Type.Ground],
        fastAttacks: ["Mud Slap", "Rock Throw"],
        chargeAttacks: ["Ancient Power", "Earthquake", "Stone Edge"]),
    Pokemon(number: "#077", baseAtt: 168, baseDef: 138, baseSta: 100,
        name: ["Ponyta", "小火馬", "小火馬"],
        type: [Type.Fire],
        fastAttacks: ["Tackle", "Ember"],
        chargeAttacks: ["Fire Blast", "Flame Wheel", "Flame Charge"]),
    Pokemon(number: "#078", baseAtt: 200, baseDef: 170, baseSta: 130,
        name: ["Rapidash", "烈焰馬", "烈焰馬"],
        type: [Type.Fire],
        fastAttacks: ["Ember", "Low Kick"],
        chargeAttacks: ["Fire Blast", "Heat Wave", "Drill Run"]),
    Pokemon(number: "#079", baseAtt: 110, baseDef: 110, baseSta: 180,
        name: ["Slowpoke", "呆呆獸", "小呆獸"],
        type: [Type.Water, Type.Psychic],
        fastAttacks: ["Confusion", "Water Gun"],
        chargeAttacks: ["Psychic", "Psyshock", "Water Pulse"]),
    Pokemon(number: "#080", baseAtt: 184, baseDef: 198, baseSta: 190,
        name: ["Slowbro", "呆河馬", "大呆獸"],
        type: [Type.Water, Type.Psychic],
        fastAttacks: ["Confusion", "Water Gun"],
        chargeAttacks: ["Ice Beam", "Psychic", "Water Pulse"]),
    Pokemon(number: "#081", baseAtt: 128, baseDef: 138, baseSta: 50,
        name: ["Magnemite", "小磁怪", "小磁怪"],
        type: [Type.Electric, Type.Steel],
        fastAttacks: ["Spark", "Thunder Shock"],
        chargeAttacks: ["Discharge", "Magnet Bomb", "Thunderbolt"]),
    Pokemon(number: "#082", baseAtt: 186, baseDef: 180, baseSta: 100,
        name: ["Magneton", "三合一磁怪", "三合一磁怪"],
        type: [Type.Electric, Type.Steel],
        fastAttacks: ["Spark", "Thunder Shock"],
        chargeAttacks: ["Discharge", "Flash Cannon", "Magnet Bomb"]),
    Pokemon(number: "#083", baseAtt: 138, baseDef: 132, baseSta: 104,
        name: ["Farfetch'd", "大蔥鴨", "火蔥鴨"],
        type: [Type.Normal, Type.Flying],
        fastAttacks: ["Fury Cutter", "Cut"],
        chargeAttacks: ["Aerial Ace", "Air Cutter", "Leaf Blade"]),
    Pokemon(number: "#084", baseAtt: 126, baseDef: 96, baseSta: 70,
        name: ["Doduo", "嘟嘟", "多多"],
        type: [Type.Normal, Type.Flying],
        fastAttacks: ["Peck", "Quick Attack"],
        chargeAttacks: ["Aerial Ace", "Drill Peck", "Swift"]),
    Pokemon(number: "#085", baseAtt: 182, baseDef: 150, baseSta: 120,
        name: ["Dodrio", "嘟嘟利", "多多利"],
        type: [Type.Normal, Type.Flying],
        fastAttacks: ["Feint Attack", "Steel Wing"],
        chargeAttacks: ["Aerial Ace", "Air Cutter", "Drill Peck"]),
    Pokemon(number: "#086", baseAtt: 104, baseDef: 138, baseSta: 130,
        name: ["Seel", "小海獅", "小海獅"],
        type: [Type.Water],
        fastAttacks: ["Lick", "Ice Shard"],
        chargeAttacks: ["Aqua Jet", "Aqua Tail", "Icy Wind"]),
    Pokemon(number: "#087", baseAtt: 156, baseDef: 192, baseSta: 180,
        name: ["Dewgong", "白海獅", "白海獅"],
        type: [Type.Water, Type.Ice],
        fastAttacks: ["Frost Breath", "Ice Shard"],
        chargeAttacks: ["Aqua Jet", "Blizzard", "Icy Wind"]),
    Pokemon(number: "#088", baseAtt: 124, baseDef: 110, baseSta: 160,
        name: ["Grimer", "臭泥", "爛泥怪"],
        type: [Type.Poison],
        fastAttacks: ["Mud Slap", "Poison Jab"],
        chargeAttacks: ["Mud Bomb", "Sludge", "Sludge Bomb"]),
    Pokemon(number: "#089", baseAtt: 180, baseDef: 188, baseSta: 210,
        name: ["Muk", "臭臭泥", "爛泥獸"],
        type: [Type.Poison],
        fastAttacks: ["Lick", "Poison Jab"],
        chargeAttacks: ["Dark Pulse", "Gunk Shot", "Sludge Wave"]),
    Pokemon(number: "#090", baseAtt: 120, baseDef: 112, baseSta: 60,
        name: ["Shellder", "大舌貝", "貝殼怪"],
        type: [Type.Water],
        fastAttacks: ["Tackle", "Ice Shard"],
        chargeAttacks: ["Bubble Beam", "Icy Wind", "Water Pulse"]),
    Pokemon(number: "#091", baseAtt: 196, baseDef: 196, baseSta: 100,
        name: ["Cloyster", "鐵甲貝", "鐵甲貝"],
        type: [Type.Water, Type.Ice],
        fastAttacks: ["Frost Breath", "Ice Shard"],
        chargeAttacks: ["Blizzard", "Hydro Pump", "Icy Wind"]),
    Pokemon(number: "#092", baseAtt: 136, baseDef: 82, baseSta: 60,
        name: ["Gastly", "鬼斯", "鬼斯"],
        type: [Type.Ghost, Type.Poison],
        fastAttacks: ["Lick", "Sucker Punch"],
        chargeAttacks: ["Dark Pulse", "Sludge Bomb", "Ominous Wind"]),
    Pokemon(number: "#093", baseAtt: 172, baseDef: 118, baseSta: 90,
        name: ["Haunter", "鬼斯通", "鬼斯通"],
        type: [Type.Ghost, Type.Poison],
        fastAttacks: ["Lick", "Shadow Claw"],
        chargeAttacks: ["Dark Pulse", "Shadow Ball", "Sludge Bomb"]),
    Pokemon(number: "#094", baseAtt: 204, baseDef: 156, baseSta: 120,
        name: ["Gengar", "耿鬼", "耿鬼"],
        type: [Type.Ghost, Type.Poison],
        fastAttacks: ["Sucker Punch", "Shadow Claw"],
        chargeAttacks: ["Dark Pulse", "Shadow Ball", "Sludge Bomb"]),
    Pokemon(number: "#095", baseAtt: 90, baseDef: 186, baseSta: 70,
        name: ["Onix", "大岩蛇", "大岩蛇"],
        type: [Type.Rock, Type.Ground],
        fastAttacks: ["Tackle", "Rock Throw"],
        chargeAttacks: ["Iron Head", "Rock Slide", "Stone Edge"]),
    Pokemon(number: "#096", baseAtt: 104, baseDef: 140, baseSta: 120,
        name: ["Drowzee", "素利普", "食夢獸"],
        type: [Type.Psychic],
        fastAttacks: ["Confusion", "Pound"],
        chargeAttacks: ["Psybeam", "Psychic", "Psyshock"]),
    Pokemon(number: "#097", baseAtt: 162, baseDef: 196, baseSta: 170,
        name: ["Hypno", "素利拍", "催眠獸"],
        type: [Type.Psychic],
        fastAttacks: ["Confusion", "Zen Headbutt"],
        chargeAttacks: ["Psychic", "Psyshock", "Shadow Ball"]),
    Pokemon(number: "#098", baseAtt: 178, baseDef: 168, baseSta: 110,
        name: ["Kingler", "巨鉗蟹", "巨鉗蟹"],
        type: [Type.Water],
        fastAttacks: ["Bubble", "Mud Shot"],
        chargeAttacks: ["Bubble Beam", "Vice Grip", "Water Pulse"]),
    Pokemon(number: "#099", baseAtt: 116, baseDef: 110, baseSta: 60,
        name: ["Krabby", "大鉗蟹", "大鉗蟹"],
        type: [Type.Water],
        fastAttacks: ["Metal Claw", "Mud Shot"],
        chargeAttacks: ["Vice Grip", "Water Pulse", "X-Scissor"]),
    Pokemon(number: "#100", baseAtt: 102, baseDef: 124, baseSta: 80,
        name: ["Voltorb", "雷電球", "霹靂彈"],
        type: [Type.Electric],
        fastAttacks: ["Tackle", "Spark"],
        chargeAttacks: ["Discharge", "Signal Beam", "Thunderbolt"]),
    Pokemon(number: "#101", baseAtt: 150, baseDef: 174, baseSta: 120,
        name: ["Electrode", "頑皮彈", "雷霆彈"],
        type: [Type.Electric],
        fastAttacks: ["Tackle", "Spark"],
        chargeAttacks: ["Discharge", "Hyper Beam", "Thunderbolt"]),
    Pokemon(number: "#102", baseAtt: 110, baseDef: 132, baseSta: 120,
        name: ["Exeggcute", "蛋蛋", "蛋蛋"],
        type: [Type.Grass, Type.Psychic],
        fastAttacks: ["Confusion"],
        chargeAttacks: ["Ancient Power", "Psychic", "Seed Bomb"]),
    Pokemon(number: "#103", baseAtt: 232, baseDef: 164, baseSta: 190,
        name: ["Exeggutor", "椰蛋樹", "椰樹獸"],
        type: [Type.Grass, Type.Psychic],
        fastAttacks: ["Confusion", "Zen Headbutt"],
        chargeAttacks: ["Psychic", "Seed Bomb", "Solar Beam"]),
    Pokemon(number: "#104", baseAtt: 102, baseDef: 150, baseSta: 100,
        name: ["Cubone", "可拉可拉", "卡拉卡拉"],
        type: [Type.Ground],
        fastAttacks: ["Mud Slap", "Rock Smash"],
        chargeAttacks: ["Bone Club", "Bulldoze", "Dig"]),
    Pokemon(number: "#105", baseAtt: 140, baseDef: 202, baseSta: 120,
        name: ["Marowak", "嘎啦嘎啦", "格拉格拉"],
        type: [Type.Ground],
        fastAttacks: ["Mud Slap", "Rock Smash"],
        chargeAttacks: ["Bone Club", "Dig", "Earthquake"]),
    Pokemon(number: "#106", baseAtt: 148, baseDef: 172, baseSta: 100,
        name: ["Hitmonlee", "沙瓦郎", "沙古拉"],
        type: [Type.Fighting],
        fastAttacks: ["Low Kick", "Rock Smash"],
        chargeAttacks: ["Brick Break", "Low Sweep", "Stone Edge"]),
    Pokemon(number: "#107", baseAtt: 138, baseDef: 204, baseSta: 100,
        name: ["Hitmonchan", "艾比郎", "比華拉"],
        type: [Type.Fighting],
        fastAttacks: ["Bullet Punch", "Rock Smash"],
        chargeAttacks: ["Brick Break", "Fire Punch", "Ice Punch", "Thunder Punch"]),
    Pokemon(number: "#108", baseAtt: 126, baseDef: 160, baseSta: 180,
        name: ["Lickitung", "大舌頭", "大舌頭"],
        type: [Type.Normal],
        fastAttacks: ["Lick", "Zen Headbutt"],
        chargeAttacks: ["Hyper Beam", "Power Whip", "Stomp"]),
    Pokemon(number: "#109", baseAtt: 136, baseDef: 142, baseSta: 80,
        name: ["Koffing", "瓦斯彈", "毒氣丸"],
        type: [Type.Poison],
        fastAttacks: ["Tackle"],
        chargeAttacks: ["Dark Pulse", "Sludge", "Sludge Bomb"]),
    Pokemon(number: "#110", baseAtt: 190, baseDef: 198, baseSta: 130,
        name: ["Weezing", "雙彈瓦斯", "毒氣雙子"],
        type: [Type.Poison],
        fastAttacks: ["Tackle"],
        chargeAttacks: ["Dark Pulse", "Shadow Ball", "Sludge Bomb"]),
    Pokemon(number: "#111", baseAtt: 110, baseDef: 116, baseSta: 160,
        name: ["Rhyhorn", "鐵甲犀牛", "鐵甲犀牛"],
        type: [Type.Ground, Type.Rock],
        fastAttacks: ["Mud Slap", "Rock Smash"],
        chargeAttacks: ["Bulldoze", "Horn Attack", "Stomp"]),
    Pokemon(number: "#112", baseAtt: 166, baseDef: 160, baseSta: 210,
        name: ["Rhydon", "鐵甲暴龍", "鐵甲暴龍"],
        type: [Type.Ground, Type.Rock],
        fastAttacks: ["Mud Slap", "Rock Smash"],
        chargeAttacks: ["Earthquake", "Megahorn", "Stone Edge"]),
    Pokemon(number: "#113", baseAtt: 40, baseDef: 60, baseSta: 500,
        name: ["Chansey", "吉利蛋", "吉利蛋"],
        type: [Type.Normal],
        fastAttacks: ["Pound", "Zen Headbutt"],
        chargeAttacks: ["Dazzling Gleam", "Hyper Beam", "Psychic"]),
    Pokemon(number: "#114", baseAtt: 164, baseDef: 152, baseSta: 130,
        name: ["Tangela", "蔓藤怪", "長藤怪"],
        type: [Type.Grass],
        fastAttacks: ["Vine Whip"],
        chargeAttacks: ["Power Whip", "Sludge Bomb", "Solar Beam"]),
    Pokemon(number: "#115", baseAtt: 142, baseDef: 178, baseSta: 210,
        name: ["Kangaskhan", "袋龍", "袋獸"],
        type: [Type.Normal],
        fastAttacks: ["Low Kick", "Mud Slap"],
        chargeAttacks: ["Brick Break", "Earthquake", "Stomp"]),
    Pokemon(number: "#116", baseAtt: 122, baseDef: 100, baseSta: 60,
        name: ["Horsea", "墨海馬", "噴墨海馬"],
        type: [Type.Water],
        fastAttacks: ["Bubble", "Water Gun"],
        chargeAttacks: ["Bubble Beam", "Dragon Pulse", "Flash Cannon"]),
    Pokemon(number: "#117", baseAtt: 176, baseDef: 150, baseSta: 110,
        name: ["Seadra", "海刺龍", "飛刺海馬"],
        type: [Type.Water],
        fastAttacks: ["Dragon Breath", "Water Gun"],
        chargeAttacks: ["Blizzard", "Dragon Pulse", "Hydro Pump"]),
    Pokemon(number: "#118", baseAtt: 112, baseDef: 126, baseSta: 90,
        name: ["Goldeen", "角金魚", "獨角金魚"],
        type: [Type.Water],
        fastAttacks: ["Mud Shot", "Peck"],
        chargeAttacks: ["Aqua Tail", "Horn Attack", "Water Pulse"]),
    Pokemon(number: "#119", baseAtt: 172, baseDef: 160, baseSta: 160,
        name: ["Seaking", "金魚王", "金魚王"],
        type: [Type.Water],
        fastAttacks: ["Peck", "Poison Jab"],
        chargeAttacks: ["Icy Wind", "Megahorn", "Drill Run"]),
    Pokemon(number: "#120", baseAtt: 130, baseDef: 128, baseSta: 60,
        name: ["Staryu", "海星星", "海星星"],
        type: [Type.Water],
        fastAttacks: ["Tackle", "Water Gun"],
        chargeAttacks: ["Bubble Beam", "Power Gem", "Swift"]),
    Pokemon(number: "#121", baseAtt: 194, baseDef: 192, baseSta: 120,
        name: ["Starmie", "寶石海星", "寶石海星"],
        type: [Type.Water, Type.Psychic],
        fastAttacks: ["Tackle", "Water Gun"],
        chargeAttacks: ["Hydro Pump", "Power Gem", "Psychic"]),
    Pokemon(number: "#122", baseAtt: 154, baseDef: 196, baseSta: 80,
        name: ["Mr. Mime", "吸盤魔偶", "吸盤小丑"],
        type: [Type.Psychic, Type.Fairy],
        fastAttacks: ["Confusion", "Zen Headbutt"],
        chargeAttacks: ["Psybeam", "Psychic", "Shadow Ball"]),
    Pokemon(number: "#123", baseAtt: 176, baseDef: 180, baseSta: 140,
        name: ["Scyther", "飛天螳螂", "飛天螳螂"],
        type: [Type.Bug, Type.Flying],
        fastAttacks: ["Fury Cutter", "Steel Wing"],
        chargeAttacks: ["Bug Buzz", "Night Slash", "X-Scissor"]),
    Pokemon(number: "#124", baseAtt: 172, baseDef: 134, baseSta: 130,
        name: ["Jynx", "迷唇姐", "紅唇娃"],
        type: [Type.Ice, Type.Psychic],
        fastAttacks: ["Frost Breath", "Pound"],
        chargeAttacks: ["Draining Kiss", "Ice Punch", "Psyshock"]),
    Pokemon(number: "#125", baseAtt: 198, baseDef: 160, baseSta: 130,
        name: ["Electabuzz", "電擊獸", "電擊獸"],
        type: [Type.Electric],
        fastAttacks: ["Low Kick", "Thunder Shock"],
        chargeAttacks: ["Thunder", "Thunder Punch", "Thunderbolt"]),
    Pokemon(number: "#126", baseAtt: 214, baseDef: 158, baseSta: 130,
        name: ["Magmar", "鴨嘴火龍", "鴨嘴火龍"],
        type: [Type.Fire],
        fastAttacks: ["Ember", "Karate Chop"],
        chargeAttacks: ["Fire Blast", "Fire Punch", "Flamethrower"]),
    Pokemon(number: "#127", baseAtt: 184, baseDef: 186, baseSta: 130,
        name: ["Pinsir", "大甲", "鉗刀甲蟲"],
        type: [Type.Bug],
        fastAttacks: ["Fury Cutter", "Rock Smash"],
        chargeAttacks: ["Submission", "Vice Grip", "X-Scissor"]),
    Pokemon(number: "#128", baseAtt: 148, baseDef: 184, baseSta: 150,
        name: ["Tauros", "肯泰羅", "大隻牛"],
        type: [Type.Normal],
        fastAttacks: ["Tackle", "Zen Headbutt"],
        chargeAttacks: ["Earthquake", "Horn Attack", "Iron Head"]),
    Pokemon(number: "#129", baseAtt: 42, baseDef: 84, baseSta: 40,
        name: ["Magikarp", "鯉魚王", "鯉魚王"],
        type: [Type.Water],
        fastAttacks: ["Splash"],
        chargeAttacks: ["Struggle"]),
    Pokemon(number: "#130", baseAtt: 192, baseDef: 196, baseSta: 190,
        name: ["Gyarados", "暴鯉龍", "鯉魚龍"],
        type: [Type.Water, Type.Flying],
        fastAttacks: ["Bite"],
        chargeAttacks: ["Dragon Pulse", "Hydro Pump", "Twister"]),
    Pokemon(number: "#131", baseAtt: 186, baseDef: 190, baseSta: 260,
        name: ["Lapras", "乘龍", "背背龍"],
        type: [Type.Water, Type.Ice],
        fastAttacks: ["Frost Breath", "Ice Shard"],
        chargeAttacks: ["Blizzard", "Dragon Pulse", "Ice Beam"]),
    Pokemon(number: "#132", baseAtt: 110, baseDef: 110, baseSta: 96,
        name: ["Ditto", "百變怪", "百變怪"],
        type: [Type.Normal],
        fastAttacks: ["Pound"],
        chargeAttacks: ["Struggle"]),
    Pokemon(number: "#133", baseAtt: 114, baseDef: 128, baseSta: 110,
        name: ["Eevee", "伊布", "伊貝"],
        type: [Type.Normal],
        fastAttacks: ["Tackle", "Quick Attack"],
        chargeAttacks: ["Body Slam", "Dig", "Swift"]),
    Pokemon(number: "#134", baseAtt: 186, baseDef: 168, baseSta: 260,
        name: ["Vaporeon", "水精靈", "水伊貝"],
        type: [Type.Water],
        fastAttacks: ["Water Gun"],
        chargeAttacks: ["Aqua Tail", "Hydro Pump", "Water Pulse"]),
    Pokemon(number: "#135", baseAtt: 192, baseDef: 174, baseSta: 130,
        name: ["Jolteon", "雷精靈", "雷伊貝"],
        type: [Type.Electric],
        fastAttacks: ["Thunder Shock"],
        chargeAttacks: ["Discharge", "Thunder", "Thunderbolt"]),
    Pokemon(number: "#136", baseAtt: 238, baseDef: 178, baseSta: 130,
        name: ["Flareon", "火精靈", "火伊貝"],
        type: [Type.Fire],
        fastAttacks: ["Ember"],
        chargeAttacks: ["Fire Blast", "Flamethrower", "Heat Wave"]),
    Pokemon(number: "#137", baseAtt: 156, baseDef: 158, baseSta: 130,
        name: ["Porygon", "3D龍", "立方獸"],
        type: [Type.Normal],
        fastAttacks: ["Tackle", "Zen Headbutt"],
        chargeAttacks: ["Discharge", "Psybeam", "Signal Beam"]),
    Pokemon(number: "#138", baseAtt: 132, baseDef: 160, baseSta: 70,
        name: ["Omanyte", "菊石獸", "菊石獸"],
        type: [Type.Rock, Type.Water],
        fastAttacks: ["Mud Shot", "Water Gun"],
        chargeAttacks: ["Ancient Power", "Rock Tomb", "Brine"]),
    Pokemon(number: "#139", baseAtt: 180, baseDef: 202, baseSta: 140,
        name: ["Omastar", "多刺菊石獸", "多刺菊石獸"],
        type: [Type.Rock, Type.Water],
        fastAttacks: ["Mud Shot", "Water Gun"],
        chargeAttacks: ["Ancient Power", "Hydro Pump", "Rock Slide"]),
    Pokemon(number: "#140", baseAtt: 148, baseDef: 142, baseSta: 60,
        name: ["Kabuto", "化石盔", "萬年蟲"],
        type: [Type.Rock, Type.Water],
        fastAttacks: ["Mud Shot", "Scratch"],
        chargeAttacks: ["Ancient Power", "Aqua Jet", "Rock Tomb"]),
    Pokemon(number: "#141", baseAtt: 190, baseDef: 190, baseSta: 120,
        name: ["Kabutops", "鐮刀盔", "鐮刀蟲"],
        type: [Type.Rock, Type.Water],
        fastAttacks: ["Fury Cutter", "Mud Shot"],
        chargeAttacks: ["Ancient Power", "Stone Edge", "Water Pulse"]),
    Pokemon(number: "#142", baseAtt: 182, baseDef: 162, baseSta: 160,
        name: ["Aerodactyl", "化石翼龍", "化石飛龍"],
        type: [Type.Rock, Type.Flying],
        fastAttacks: ["Bite", "Steel Wing"],
        chargeAttacks: ["Ancient Power", "Hyper Beam", "Iron Head"]),
    Pokemon(number: "#143", baseAtt: 180, baseDef: 180, baseSta: 320,
        name: ["Snorlax", "卡比獸", "卡比獸"],
        type: [Type.Normal],
        fastAttacks: ["Lick", "Zen Headbutt"],
        chargeAttacks: ["Body Slam", "Earthquake", "Hyper Beam"]),
    Pokemon(number: "#144", baseAtt: 198, baseDef: 242, baseSta: 180,
        name: ["Articuno", "急凍鳥", "急凍鳥"],
        type: [Type.Ice, Type.Flying],
        fastAttacks: ["Frost Breath"],
        chargeAttacks: ["Blizzard", "Ice Beam", "Icy Wind"]),
    Pokemon(number: "#145", baseAtt: 232, baseDef: 194, baseSta: 180,
        name: ["Zapdos", "閃電鳥", "雷鳥"],
        type: [Type.Electric, Type.Flying],
        fastAttacks: ["Thunder Shock"],
        chargeAttacks: ["Discharge", "Thunder", "Thunderbolt"]),
    Pokemon(number: "#146", baseAtt: 242, baseDef: 194, baseSta: 180,
        name: ["Moltres", "火焰鳥", "火鳥"],
        type: [Type.Fire, Type.Flying],
        fastAttacks: ["Ember"],
        chargeAttacks: ["Fire Blast", "Flamethrower", "Heat Wave"]),
    Pokemon(number: "#147", baseAtt: 128, baseDef: 110, baseSta: 82,
        name: ["Dratini", "迷你龍", "迷你龍"],
        type: [Type.Dragon],
        fastAttacks: ["Bite", "Dragon Breath"],
        chargeAttacks: ["Aqua Tail", "Twister", "Wrap"]),
    Pokemon(number: "#148", baseAtt: 170, baseDef: 152, baseSta: 122,
        name: ["Dragonair", "哈克龍", "哈古龍"],
        type: [Type.Dragon],
        fastAttacks: ["Dragon Breath", "Steel Wing"],
        chargeAttacks: ["Aqua Tail", "Dragon Pulse", "Wrap"]),
    Pokemon(number: "#149", baseAtt: 250, baseDef: 212, baseSta: 182,
        name: ["Dragonite", "快龍", "啟暴龍"],
        type: [Type.Dragon, Type.Flying],
        fastAttacks: ["Dragon Breath", "Steel Wing"],
        chargeAttacks: ["Dragon Claw", "Dragon Pulse", "Hyper Beam"]),
    Pokemon(number: "#150", baseAtt: 284, baseDef: 202, baseSta: 212,
        name: ["Mewtwo", "超夢", "超夢夢"],
        type: [Type.Psychic],
        fastAttacks: ["Confusion", "Psycho Cut"],
        chargeAttacks: ["Hyper Beam", "Psychic", "Shadow Ball"]),
    Pokemon(number: "#151", baseAtt: 220, baseDef: 220, baseSta: 200,
        name: ["Mew", "夢幻", "夢夢"],
        type: [Type.Psychic],
        fastAttacks: ["Pound"],
        chargeAttacks: ["Blizzard", "Dragon Pulse", "Earthquake", "Fire Blast", "Hyper Beam", "Psychic", "Solar Beam", "Thunder"]),
]

